# Generated by Django 4.2.2 on 2023-06-15 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0002_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=40)),
                ('logo', models.ImageField(default='default_logo.jpeg', upload_to='images/')),
                ('about', models.TextField()),
                ('commercial_registration', models.IntegerField()),
                ('pick_up_enabled', models.BooleanField(default=True)),
                ('delivery_enabled', models.BooleanField(default=True)),
                ('twitter_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('snapchat_link', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='merchant_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='customer_profile',
        ),
        migrations.DeleteModel(
            name='merchant_profile',
        ),
    ]
