# Generated by Django 4.2.2 on 2023-06-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_profile_store_remove_merchant_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('Saudi-Arabian', 'Saudi-Arabian'), ('Syrian', 'Syrian'), ('Egyptian', 'Egyptian'), ('Indian', 'Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Mixed', 'Mixed')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
