# Generated by Django 4.2.2 on 2023-06-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(default='images/default_logo.jpeg', upload_to='images/'),
        ),
    ]
