# Generated by Django 4.2.2 on 2023-06-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_product_image_alter_store_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
