# Generated by Django 4.2.2 on 2023-06-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('Pick_Up', 'Pick Up'), ('Delivery', 'Delivery')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('cod', 'Cash on Delivery')], max_length=50),
        ),
    ]
