# Generated by Django 4.2.2 on 2023-06-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_cart_delivery_option_alter_cart_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
