# Generated by Django 4.2.2 on 2023-06-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_cart_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
